# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk.xci
# IP: The module: 'pll_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk.xci
# IP: The module: 'pll_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
