# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath E:/FPGA/modelsim/win64
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.cache/wt [current_project]
set_property parent.project_path F:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/F_prj/ofdm_7.12/src/IFFT/IFFT.v
  F:/F_prj/ofdm_7.12/src/sequence_train/LTS_generator.v
  F:/F_prj/ofdm_7.12/src/sequence_train/STS_generator.v
  F:/F_prj/ofdm_7.12/src/cp_adder/cp_adder.v
  F:/F_prj/ofdm_7.12/src/ofdm_data_modem/data_conv_code.v
  F:/F_prj/ofdm_7.12/src/ofdm_data_modem/data_interleaver.v
  F:/F_prj/ofdm_7.12/src/ofdm_data_modem/data_mapping.v
  F:/F_prj/ofdm_7.12/src/ofdm_data_modem/data_pilot_insert.v
  F:/F_prj/ofdm_7.12/src/ofdm_data_modem/data_puncturing.v
  F:/F_prj/ofdm_7.12/src/ofdm_data_modem/data_scramler.v
  F:/F_prj/ofdm_7.12/src/ofdm_data_modem/ofdm_data_modem.v
  F:/F_prj/ofdm_7.12/src/ofdm_data_modem/spram_128.v
  F:/F_prj/ofdm_7.12/src/cp_adder/spram_64.v
  F:/F_prj/ofdm_7.12/src/sequence_train/symbol_train.v
  F:/F_prj/ofdm_7.12/src/ofdm_data_modem/sync_buffer.v
  F:/F_prj/ofdm_7.12/src/trans_mcu/trans_mcu.v
  F:/F_prj/ofdm_7.12/src/ofdm_transmitter.v
}
read_ip -quiet F:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fifo_mcu/fifo_mcu.xci
set_property used_in_implementation false [get_files -all f:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fifo_mcu/fifo_mcu.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fifo_mcu/fifo_mcu_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fifo_mcu/fifo_mcu_ooc.xdc]

read_ip -quiet F:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fifo_asyn/fifo_asyn.xci
set_property used_in_implementation false [get_files -all f:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fifo_asyn/fifo_asyn.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fifo_asyn/fifo_asyn_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fifo_asyn/fifo_asyn_ooc.xdc]

read_ip -quiet F:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fft/fft.xci
set_property used_in_implementation false [get_files -all f:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fft/fft_ooc.xdc]

read_ip -quiet F:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk.xci
set_property used_in_implementation false [get_files -all f:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk_board.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/sources_1/ip/pll_clk/pll_clk_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/constrs_1/new/time.xdc
set_property used_in_implementation false [get_files F:/F_prj/ofdm_7.12/ofdm_tx/ofdm_tx.srcs/constrs_1/new/time.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ofdm_transmitter -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ofdm_transmitter.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ofdm_transmitter_utilization_synth.rpt -pb ofdm_transmitter_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
