# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fft/fft.xci
# IP: The module: 'fft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fft/fft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fft/fft.xci
# IP: The module: 'fft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/F_prj/ofdm/ofdm_tx/ofdm_tx.srcs/sources_1/ip/fft/fft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
